spring.application.name=chat-app
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username= db_user
spring.datasource.password= DB_Connect_294
spring.flyway.baselineOnMigrate=true